# Generated by Django 3.2.8 on 2021-10-31 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('put_date', models.DateField()),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='imagesBlog/')),
            ],
        ),
    ]
