# Generated by Django 3.2.8 on 2021-11-01 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='put_date',
            field=models.DateTimeField(),
        ),
    ]
